[package]
author = "Michele Cioccarelli"
name = "blob-dl"
version = "0.1.0"
description = "Neat wrapper goes brr (short about)"
repository = "https://github.com/MicheleCioccarelli/blob-dl"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
execute = "0.2.11"
requestty = "0.5.0"
url = "2.3.1"
