[package]
author = "Michele Cioccarelli"
name = "blob-dl"
version = "0.1.0"
description = "Neat wrapper goes brr (short about)"
repository = "https://github.com/MicheleCioccarelli/blob-dl"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
colored = "2.0.0"
dialoguer = "0.10.2"
execute = "0.2.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
spinoff = "0.6.0"
url = "2.3.1"
which = "4.4.0"
