
use clap::{Arg, ArgMatches};

use std::path::PathBuf;

use clap::{arg, command, value_parser, ArgAction, Command};

use crate::ui_prompts::*;
use crate::error::{BlobdlError, BlobResult};

pub fn parse_config() -> BlobResult<CliConfig> {
    let matches = Command::new("blob-dl")
        .version("1.0.3")
        .author("cioccarellimi@gmail.com")
        .about(SHORT_ABOUT)
        .long_about(LONG_ABOUT)
        .arg(
            Arg::new("verbose")
                .short('v')
                .long("verbose")
                .help("Show all the output produced by yt-dlp")
                .action(ArgAction::SetTrue),
        )
        .arg(
            Arg::new("quiet")
                .short('q')
                .long("quiet")
                .help("Silence all output except for the final error summary")
                .action(ArgAction::SetTrue),
        )
        .arg(
            Arg::new("show-command")
                .help("Print to the console the command generated by blob-dl")
                .long("show-command")
                .short('s')
                .action(ArgAction::SetTrue),
        )
        .arg(
            Arg::new("generate-config")
                .help("Saves your downloading preferences in a config file. For more information refer to blob-dl's GitHub page")
                .long("generate-config")
                .short('g')
                .action(ArgAction::SetTrue),
        )
        .arg(
            Arg::new("use-config-file")
                .help("Use the preferences from a config file instead of asking questions. This command will look for a config file in blob-dl's default location")
                .long("use-config")
                .short('c')
                .action(ArgAction::SetTrue),
        )
        .arg(
            arg!(
                -l --"locate-config-file" <FILE> "Use the preferences from a config file. This command will look for a config file in the path you provide"
            )
                .required(false)
                .value_parser(value_parser!(PathBuf)),
        )
        .arg(Arg::new("URL")
            .help("Link to the youtube video/playlist that you want to download")
        )
        .get_matches();
    
    CliConfig::from(matches)
}

/// The 3 possible verbosity options for this program
#[derive(Debug)]
pub enum Verbosity {
    Verbose,
    Default,
    Quiet,
}

#[derive(Debug)]
pub enum ConfigFilePreferences {
    /// Don't do anything related to config files
    NoConfig,
    /// Search for the config file in blob-dl's default location
    DefaultConfig,
    /// Search for the config file in a user-defined directory
    CustomConfig(PathBuf),
    /// Create a config file based on the user's answers and place it in blob-dl's default location
    GenerateConfig,
}

/// Holds all the information that can be fetched as a command line argument
#[derive(Debug)]
pub struct CliConfig {
    // Refs to this String are stored in other Config objects
    url: String,
    verbosity: Verbosity,
    // Whether to print to the console the final command which is the run by yt-dlp
    show_command: bool,

    pub config_file_preference: ConfigFilePreferences,
}

impl CliConfig {
    /// Constructs a CliConfig object based on Clap's output
    pub fn from(matches: ArgMatches) -> BlobResult<CliConfig> {

        let url = match matches.get_one::<String>("URL") {
            Some(url) => url.clone(),
            None => return Err(BlobdlError::MissingArgument),
        };

        let verbosity = {
            if matches.get_flag("quiet") {
                Verbosity::Quiet
            }
            else if matches.get_flag("verbose") {
                Verbosity::Verbose
            }
            else {
                Verbosity::Default
            }
        };
        let show_command = matches.get_flag("show-command");

        // The user is supposed to only use one of these at a time
        let mut config_file_preference = ConfigFilePreferences::NoConfig;
        if let Some(path) = matches.get_one::<PathBuf>("locate-config-file") {
            config_file_preference = ConfigFilePreferences::CustomConfig(path.clone());
        };
        if matches.get_flag("generate-config") {
            config_file_preference = ConfigFilePreferences::GenerateConfig;
        } else if matches.get_flag("use-config-file") {
            config_file_preference = ConfigFilePreferences::DefaultConfig;
        }

        Ok(CliConfig {
            url,
            verbosity,
            show_command,
            config_file_preference
        })
    }

    pub fn url(&self) -> &String {
        &self.url
    }
    pub fn verbosity(&self) -> &Verbosity {
        &self.verbosity
    }
    pub fn show_command(&self) -> bool {
        self.show_command
    }
    pub fn config_file_preference(&self) -> &ConfigFilePreferences {
        &self.config_file_preference
    }
}

/// Check if the user has a version of ytdlp compatible with blob-dl (now it is 2024.11.18)
pub fn is_ytdlp_compatible() ->Result<bool, BlobdlError> {
    let version = std::process::Command::new("yt-dlp")
            .arg("--version")
            .output();
    
    if let Ok(version) = version {
        let str = std::str::from_utf8(&version.stdout)?;

        if str == "2024.11.18\n" {
            Ok(true)
        } else {
            Ok(false)
        }
        
    } else {
        Err(BlobdlError::CommandNotSpawned)
    }
}